-- MySQL Script generated by MySQL Workbench
-- Sat Jul 17 21:08:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- Schema khoot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `khoot` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- -----------------------------------------------------
USE `khoot` ;

-- -----------------------------------------------------
-- Table `khoot`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khoot`.`role` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khoot`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khoot`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `is_deleted` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `address` TINYTEXT NULL DEFAULT NULL,
  `role_id` INT(11) NOT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '1',
  `verified_token` MEDIUMTEXT NULL DEFAULT NULL,
  `email_verified` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_idx` (`role_id` ASC) ,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `khoot`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khoot`.`assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khoot`.`assessment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `time` INT NULL,
  `id_deleted` INT NULL DEFAULT 0,
  `description` MEDIUMTEXT NULL,
  `number_of_question` INT NULL,
  `status` INT NULL,
  `user_id` INT(11) NOT NULL,
  `join_key` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assessment_user1_idx` (`user_id` ASC) ,
  UNIQUE INDEX `join_key_UNIQUE` (`join_key` ASC) ,
  CONSTRAINT `fk_assessment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `khoot`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `khoot`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khoot`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` MEDIUMTEXT NULL,
  `type` INT NULL,
  `answers` MEDIUMTEXT NULL,
  `full_answers` MEDIUMTEXT NULL,
  `point` INT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `image` VARCHAR(255) NULL,
  `assessment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_assessment_idx` (`assessment_id` ASC) ,
  CONSTRAINT `fk_question_assessment`
    FOREIGN KEY (`assessment_id`)
    REFERENCES `khoot`.`assessment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `khoot`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khoot`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `khoot`.`result_assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khoot`.`result_assessment` (
  `player_id` INT NOT NULL,
  `assessment_id` INT NOT NULL,
  `id` INT NOT NULL,
  `point` INT NULL,
  INDEX `fk_player_has_assessment_assessment1_idx` (`assessment_id` ASC) ,
  INDEX `fk_player_has_assessment_player1_idx` (`player_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_player_has_assessment_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `khoot`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_has_assessment_assessment1`
    FOREIGN KEY (`assessment_id`)
    REFERENCES `khoot`.`assessment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lasy_shop`.`user_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khoot`.`user_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `access_token` MEDIUMTEXT NULL,
  `refresh_token` MEDIUMTEXT NULL,
  `expires_in` INT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_session_user1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_user_session_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `khoot`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE `khoot`.`assessment` 
ADD COLUMN `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `join_key`,
ADD COLUMN `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `created_at`;

ALTER TABLE `khoot`.`result_assessment` 
ADD COLUMN `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `point`,
ADD COLUMN `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `created_at`;

ALTER TABLE `khoot`.`result_assessment` 
ADD COLUMN `results` VARCHAR(255) NULL AFTER `updated_at`;

ALTER TABLE `khoot`.`result_assessment` 
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

